"""Ajout du champ JSON details_json dans Vehicule

Revision ID: 16b9a6e3363d
Revises: 7fc45a33ccf5
Create Date: 2025-06-21 18:52:44.773069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b9a6e3363d'
down_revision = '7fc45a33ccf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.drop_column('details_json')

    # ### end Alembic commands ###
