"""Ajout colonne motif dans demandes_mission

Revision ID: 7fc45a33ccf5
Revises: c9d1afdb85c3
Create Date: 2025-05-19 10:00:28.710853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc45a33ccf5'
down_revision = 'c9d1afdb85c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motif', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_mission', schema=None) as batch_op:
        batch_op.drop_column('motif')

    # ### end Alembic commands ###
