"""Ajout champ archiver utilisateur

Revision ID: a037c0d1738b
Revises: e08ad96f90da
Create Date: 2025-06-25 21:22:57.675727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a037c0d1738b'
down_revision = 'e08ad96f90da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_column('archiver')

    # ### end Alembic commands ###
