"""Ajout du champ d'archivage de vehicule

Revision ID: b8b4f151078a
Revises: 2e1ebc449ee9
Create Date: 2025-06-25 18:54:54.954283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b4f151078a'
down_revision = '2e1ebc449ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.drop_column('archiver')

    # ### end Alembic commands ###
