"""Ajout champ is_assigned aux véhicules

Revision ID: c9d1afdb85c3
Revises: 17208fdae349
Create Date: 2025-05-08 17:42:57.840306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d1afdb85c3'
down_revision = '17208fdae349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_assigned', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.drop_column('is_assigned')

    # ### end Alembic commands ###
