"""Fix: ajout vehicule_id à DemandeLocation

Revision ID: cc9e60233cda
Revises: 2023f019ab53
Create Date: 2025-05-07 17:15:39.079055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9e60233cda'
down_revision = '2023f019ab53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicule_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vehicule', ['vehicule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicule_id')

    # ### end Alembic commands ###
