"""Initial migration with image_path

Revision ID: db63d7c741c6
Revises: 
Create Date: 2025-05-07 10:48:20.243775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db63d7c741c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('carburant', sa.String(length=50), nullable=False),
    sa.Column('kilometrage', sa.Integer(), nullable=False),
    sa.Column('prix_jour', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicule')
    # ### end Alembic commands ###
